// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LdapClient is the client API for Ldap service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LdapClient interface {
	SearchEmployee(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type ldapClient struct {
	cc grpc.ClientConnInterface
}

func NewLdapClient(cc grpc.ClientConnInterface) LdapClient {
	return &ldapClient{cc}
}

func (c *ldapClient) SearchEmployee(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/Ldap/SearchEmployee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LdapServer is the server API for Ldap service.
// All implementations must embed UnimplementedLdapServer
// for forward compatibility
type LdapServer interface {
	SearchEmployee(context.Context, *SearchRequest) (*SearchResponse, error)
	mustEmbedUnimplementedLdapServer()
}

// UnimplementedLdapServer must be embedded to have forward compatible implementations.
type UnimplementedLdapServer struct {
}

func (UnimplementedLdapServer) SearchEmployee(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchEmployee not implemented")
}
func (UnimplementedLdapServer) mustEmbedUnimplementedLdapServer() {}

// UnsafeLdapServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LdapServer will
// result in compilation errors.
type UnsafeLdapServer interface {
	mustEmbedUnimplementedLdapServer()
}

func RegisterLdapServer(s grpc.ServiceRegistrar, srv LdapServer) {
	s.RegisterService(&Ldap_ServiceDesc, srv)
}

func _Ldap_SearchEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LdapServer).SearchEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Ldap/SearchEmployee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LdapServer).SearchEmployee(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Ldap_ServiceDesc is the grpc.ServiceDesc for Ldap service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ldap_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Ldap",
	HandlerType: (*LdapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchEmployee",
			Handler:    _Ldap_SearchEmployee_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/ldap.proto",
}
