// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: api/staff.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Search      string `protobuf:"bytes,1,opt,name=Search,proto3" json:"Search,omitempty"`
	TableNumber string `protobuf:"bytes,2,opt,name=TableNumber,proto3" json:"TableNumber,omitempty"`
	Department  string `protobuf:"bytes,3,opt,name=Department,proto3" json:"Department,omitempty"`
	Manager     string `protobuf:"bytes,4,opt,name=Manager,proto3" json:"Manager,omitempty"`
	Job         string `protobuf:"bytes,5,opt,name=Job,proto3" json:"Job,omitempty"`
	Offset      uint32 `protobuf:"varint,6,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Limit       uint32 `protobuf:"varint,7,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Order       string `protobuf:"bytes,8,opt,name=Order,proto3" json:"Order,omitempty"`
}

func (x *GetReq) Reset() {
	*x = GetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_staff_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReq) ProtoMessage() {}

func (x *GetReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_staff_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReq.ProtoReflect.Descriptor instead.
func (*GetReq) Descriptor() ([]byte, []int) {
	return file_api_staff_proto_rawDescGZIP(), []int{0}
}

func (x *GetReq) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *GetReq) GetTableNumber() string {
	if x != nil {
		return x.TableNumber
	}
	return ""
}

func (x *GetReq) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *GetReq) GetManager() string {
	if x != nil {
		return x.Manager
	}
	return ""
}

func (x *GetReq) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

func (x *GetReq) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetReq) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetReq) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

type GetResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok    bool             `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
	Staff []*StaffEmployee `protobuf:"bytes,2,rep,name=Staff,proto3" json:"Staff,omitempty"`
}

func (x *GetResp) Reset() {
	*x = GetResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_staff_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResp) ProtoMessage() {}

func (x *GetResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_staff_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResp.ProtoReflect.Descriptor instead.
func (*GetResp) Descriptor() ([]byte, []int) {
	return file_api_staff_proto_rawDescGZIP(), []int{1}
}

func (x *GetResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *GetResp) GetStaff() []*StaffEmployee {
	if x != nil {
		return x.Staff
	}
	return nil
}

type CountResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok    bool   `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
	Count uint32 `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
}

func (x *CountResp) Reset() {
	*x = CountResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_staff_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountResp) ProtoMessage() {}

func (x *CountResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_staff_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountResp.ProtoReflect.Descriptor instead.
func (*CountResp) Descriptor() ([]byte, []int) {
	return file_api_staff_proto_rawDescGZIP(), []int{2}
}

func (x *CountResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CountResp) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type StaffEmployee struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint32                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Table      string                 `protobuf:"bytes,2,opt,name=Table,proto3" json:"Table,omitempty"`
	Name       string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Manager    string                 `protobuf:"bytes,4,opt,name=Manager,proto3" json:"Manager,omitempty"`
	Department string                 `protobuf:"bytes,5,opt,name=Department,proto3" json:"Department,omitempty"`
	Job        string                 `protobuf:"bytes,6,opt,name=Job,proto3" json:"Job,omitempty"`
	CreatedAt  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
}

func (x *StaffEmployee) Reset() {
	*x = StaffEmployee{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_staff_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaffEmployee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffEmployee) ProtoMessage() {}

func (x *StaffEmployee) ProtoReflect() protoreflect.Message {
	mi := &file_api_staff_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffEmployee.ProtoReflect.Descriptor instead.
func (*StaffEmployee) Descriptor() ([]byte, []int) {
	return file_api_staff_proto_rawDescGZIP(), []int{3}
}

func (x *StaffEmployee) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StaffEmployee) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *StaffEmployee) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StaffEmployee) GetManager() string {
	if x != nil {
		return x.Manager
	}
	return ""
}

func (x *StaffEmployee) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *StaffEmployee) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

func (x *StaffEmployee) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint32                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	PropertyId uint32                 `protobuf:"varint,2,opt,name=Property_id,json=PropertyId,proto3" json:"Property_id,omitempty"`
	StaffId    uint32                 `protobuf:"varint,3,opt,name=Staff_id,json=StaffId,proto3" json:"Staff_id,omitempty"`
	Username   string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	CreatedAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
}

func (x *SRecord) Reset() {
	*x = SRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_staff_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRecord) ProtoMessage() {}

func (x *SRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_staff_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRecord.ProtoReflect.Descriptor instead.
func (*SRecord) Descriptor() ([]byte, []int) {
	return file_api_staff_proto_rawDescGZIP(), []int{4}
}

func (x *SRecord) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SRecord) GetPropertyId() uint32 {
	if x != nil {
		return x.PropertyId
	}
	return 0
}

func (x *SRecord) GetStaffId() uint32 {
	if x != nil {
		return x.StaffId
	}
	return 0
}

func (x *SRecord) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok      bool   `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *SStatus) Reset() {
	*x = SStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_staff_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SStatus) ProtoMessage() {}

func (x *SStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_staff_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SStatus.ProtoReflect.Descriptor instead.
func (*SStatus) Descriptor() ([]byte, []int) {
	return file_api_staff_proto_rawDescGZIP(), []int{5}
}

func (x *SStatus) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatusWithEmployee struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok       bool           `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
	Employee *StaffEmployee `protobuf:"bytes,2,opt,name=Employee,proto3" json:"Employee,omitempty"`
}

func (x *StatusWithEmployee) Reset() {
	*x = StatusWithEmployee{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_staff_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusWithEmployee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusWithEmployee) ProtoMessage() {}

func (x *StatusWithEmployee) ProtoReflect() protoreflect.Message {
	mi := &file_api_staff_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusWithEmployee.ProtoReflect.Descriptor instead.
func (*StatusWithEmployee) Descriptor() ([]byte, []int) {
	return file_api_staff_proto_rawDescGZIP(), []int{6}
}

func (x *StatusWithEmployee) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StatusWithEmployee) GetEmployee() *StaffEmployee {
	if x != nil {
		return x.Employee
	}
	return nil
}

type GetStaffPropResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok    bool         `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
	Props []*StaffProp `protobuf:"bytes,2,rep,name=Props,proto3" json:"Props,omitempty"`
}

func (x *GetStaffPropResp) Reset() {
	*x = GetStaffPropResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_staff_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStaffPropResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStaffPropResp) ProtoMessage() {}

func (x *GetStaffPropResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_staff_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStaffPropResp.ProtoReflect.Descriptor instead.
func (*GetStaffPropResp) Descriptor() ([]byte, []int) {
	return file_api_staff_proto_rawDescGZIP(), []int{7}
}

func (x *GetStaffPropResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *GetStaffPropResp) GetProps() []*StaffProp {
	if x != nil {
		return x.Props
	}
	return nil
}

type StaffProp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Inventory string                 `protobuf:"bytes,2,opt,name=Inventory,proto3" json:"Inventory,omitempty"`
	Serial    string                 `protobuf:"bytes,3,opt,name=Serial,proto3" json:"Serial,omitempty"`
	Name      string                 `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	Warehouse uint32                 `protobuf:"varint,6,opt,name=Warehouse,proto3" json:"Warehouse,omitempty"`
	State     uint32                 `protobuf:"varint,7,opt,name=State,proto3" json:"State,omitempty"`
	Username  string                 `protobuf:"bytes,8,opt,name=Username,proto3" json:"Username,omitempty"`
	GivenAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=GivenAt,proto3" json:"GivenAt,omitempty"`
	RecordId  uint32                 `protobuf:"varint,10,opt,name=RecordId,proto3" json:"RecordId,omitempty"`
}

func (x *StaffProp) Reset() {
	*x = StaffProp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_staff_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaffProp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffProp) ProtoMessage() {}

func (x *StaffProp) ProtoReflect() protoreflect.Message {
	mi := &file_api_staff_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffProp.ProtoReflect.Descriptor instead.
func (*StaffProp) Descriptor() ([]byte, []int) {
	return file_api_staff_proto_rawDescGZIP(), []int{8}
}

func (x *StaffProp) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StaffProp) GetInventory() string {
	if x != nil {
		return x.Inventory
	}
	return ""
}

func (x *StaffProp) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *StaffProp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StaffProp) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *StaffProp) GetWarehouse() uint32 {
	if x != nil {
		return x.Warehouse
	}
	return 0
}

func (x *StaffProp) GetState() uint32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *StaffProp) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *StaffProp) GetGivenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GivenAt
	}
	return nil
}

func (x *StaffProp) GetRecordId() uint32 {
	if x != nil {
		return x.RecordId
	}
	return 0
}

type GiveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmployeeId uint32   `protobuf:"varint,1,opt,name=EmployeeId,proto3" json:"EmployeeId,omitempty"`
	Ids        []uint32 `protobuf:"varint,2,rep,packed,name=Ids,proto3" json:"Ids,omitempty"`
	Username   string   `protobuf:"bytes,3,opt,name=Username,proto3" json:"Username,omitempty"`
}

func (x *GiveReq) Reset() {
	*x = GiveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_staff_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GiveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiveReq) ProtoMessage() {}

func (x *GiveReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_staff_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiveReq.ProtoReflect.Descriptor instead.
func (*GiveReq) Descriptor() ([]byte, []int) {
	return file_api_staff_proto_rawDescGZIP(), []int{9}
}

func (x *GiveReq) GetEmployeeId() uint32 {
	if x != nil {
		return x.EmployeeId
	}
	return 0
}

func (x *GiveReq) GetIds() []uint32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *GiveReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetEmployeeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *GetEmployeeReq) Reset() {
	*x = GetEmployeeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_staff_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEmployeeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeReq) ProtoMessage() {}

func (x *GetEmployeeReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_staff_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeReq.ProtoReflect.Descriptor instead.
func (*GetEmployeeReq) Descriptor() ([]byte, []int) {
	return file_api_staff_proto_rawDescGZIP(), []int{10}
}

func (x *GetEmployeeReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetRecordResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Emp  *StaffEmployee         `protobuf:"bytes,1,opt,name=Emp,proto3" json:"Emp,omitempty"`
	Prop *StaffProp             `protobuf:"bytes,2,opt,name=Prop,proto3" json:"Prop,omitempty"`
	Date *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=Date,proto3" json:"Date,omitempty"`
}

func (x *GetRecordResp) Reset() {
	*x = GetRecordResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_staff_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRecordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordResp) ProtoMessage() {}

func (x *GetRecordResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_staff_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordResp.ProtoReflect.Descriptor instead.
func (*GetRecordResp) Descriptor() ([]byte, []int) {
	return file_api_staff_proto_rawDescGZIP(), []int{11}
}

func (x *GetRecordResp) GetEmp() *StaffEmployee {
	if x != nil {
		return x.Emp
	}
	return nil
}

func (x *GetRecordResp) GetProp() *StaffProp {
	if x != nil {
		return x.Prop
	}
	return nil
}

func (x *GetRecordResp) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

var File_api_staff_proto protoreflect.FileDescriptor

var file_api_staff_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xd2, 0x01, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a,
	0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x20, 0x0a, 0x0b, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x65, 0x70, 0x61, 0x72,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x44, 0x65, 0x70,
	0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x12, 0x10, 0x0a, 0x03, 0x4a, 0x6f, 0x62, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x4a, 0x6f, 0x62, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x4c, 0x69, 0x6d, 0x69,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x3f, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02,
	0x4f, 0x6b, 0x12, 0x24, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x66, 0x66, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65,
	0x65, 0x52, 0x05, 0x53, 0x74, 0x61, 0x66, 0x66, 0x22, 0x31, 0x0a, 0x09, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x02, 0x4f, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xcf, 0x01, 0x0a, 0x0d,
	0x53, 0x74, 0x61, 0x66, 0x66, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x4a, 0x6f, 0x62, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x4a, 0x6f, 0x62, 0x12, 0x38, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xab, 0x01,
	0x0a, 0x07, 0x53, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x50, 0x72, 0x6f,
	0x70, 0x65, 0x72, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a,
	0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x53, 0x74,
	0x61, 0x66, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x53, 0x74,
	0x61, 0x66, 0x66, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x38, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x33, 0x0a, 0x07, 0x53,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x02, 0x4f, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x50, 0x0a, 0x12, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x57, 0x69, 0x74, 0x68, 0x45, 0x6d,
	0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x02, 0x4f, 0x6b, 0x12, 0x2a, 0x0a, 0x08, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79,
	0x65, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x53, 0x74, 0x61, 0x66, 0x66,
	0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x08, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79,
	0x65, 0x65, 0x22, 0x44, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x66, 0x66, 0x50, 0x72,
	0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x02, 0x4f, 0x6b, 0x12, 0x20, 0x0a, 0x05, 0x50, 0x72, 0x6f, 0x70, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x50, 0x72, 0x6f,
	0x70, 0x52, 0x05, 0x50, 0x72, 0x6f, 0x70, 0x73, 0x22, 0xc1, 0x02, 0x0a, 0x09, 0x53, 0x74, 0x61,
	0x66, 0x66, 0x50, 0x72, 0x6f, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74,
	0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x49, 0x6e, 0x76, 0x65, 0x6e,
	0x74, 0x6f, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x38, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x57, 0x61,
	0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x57,
	0x61, 0x72, 0x65, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x34, 0x0a, 0x07, 0x47, 0x69,
	0x76, 0x65, 0x6e, 0x41, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x47, 0x69, 0x76, 0x65, 0x6e, 0x41, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x64, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x64, 0x22, 0x57, 0x0a, 0x07,
	0x47, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x45, 0x6d, 0x70, 0x6c, 0x6f,
	0x79, 0x65, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x45, 0x6d, 0x70,
	0x6c, 0x6f, 0x79, 0x65, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x49, 0x64, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0d, 0x52, 0x03, 0x49, 0x64, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x20, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x45, 0x6d, 0x70, 0x6c,
	0x6f, 0x79, 0x65, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x22, 0x81, 0x01, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x03, 0x45, 0x6d, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x45, 0x6d,
	0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x03, 0x45, 0x6d, 0x70, 0x12, 0x1e, 0x0a, 0x04, 0x50,
	0x72, 0x6f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x53, 0x74, 0x61, 0x66,
	0x66, 0x50, 0x72, 0x6f, 0x70, 0x52, 0x04, 0x50, 0x72, 0x6f, 0x70, 0x12, 0x2e, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x44, 0x61, 0x74, 0x65, 0x32, 0xfc, 0x02, 0x0a, 0x05,
	0x53, 0x74, 0x61, 0x66, 0x66, 0x12, 0x35, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45,
	0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x12, 0x0e, 0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x45,
	0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x1a, 0x13, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x57, 0x69, 0x74, 0x68, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x12, 0x1d, 0x0a, 0x08,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x66, 0x66, 0x12, 0x07, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x08, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2e, 0x0a, 0x0b, 0x47,
	0x65, 0x74, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x12, 0x0f, 0x2e, 0x47, 0x65, 0x74,
	0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x53, 0x74,
	0x61, 0x66, 0x66, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x12, 0x25, 0x0a, 0x09, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x08, 0x2e, 0x53, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x1a, 0x0e, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x1f, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x07,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x0a, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x31, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x66, 0x66, 0x50,
	0x72, 0x6f, 0x70, 0x12, 0x0e, 0x2e, 0x53, 0x74, 0x61, 0x66, 0x66, 0x45, 0x6d, 0x70, 0x6c, 0x6f,
	0x79, 0x65, 0x65, 0x1a, 0x11, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x66, 0x66, 0x50, 0x72,
	0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x12, 0x24, 0x0a, 0x0e, 0x47, 0x69, 0x76, 0x65, 0x54, 0x6f,
	0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x12, 0x08, 0x2e, 0x47, 0x69, 0x76, 0x65, 0x52,
	0x65, 0x71, 0x1a, 0x08, 0x2e, 0x53, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x26, 0x0a, 0x10,
	0x54, 0x61, 0x6b, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65,
	0x12, 0x08, 0x2e, 0x47, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x08, 0x2e, 0x53, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x24, 0x0a, 0x0e, 0x49, 0x73, 0x57, 0x69, 0x74, 0x68, 0x45, 0x6d,
	0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x12, 0x08, 0x2e, 0x47, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x08, 0x2e, 0x53, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x0b, 0x5a, 0x09, 0x73, 0x74,
	0x61, 0x66, 0x66, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_staff_proto_rawDescOnce sync.Once
	file_api_staff_proto_rawDescData = file_api_staff_proto_rawDesc
)

func file_api_staff_proto_rawDescGZIP() []byte {
	file_api_staff_proto_rawDescOnce.Do(func() {
		file_api_staff_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_staff_proto_rawDescData)
	})
	return file_api_staff_proto_rawDescData
}

var file_api_staff_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_staff_proto_goTypes = []interface{}{
	(*GetReq)(nil),                // 0: GetReq
	(*GetResp)(nil),               // 1: GetResp
	(*CountResp)(nil),             // 2: CountResp
	(*StaffEmployee)(nil),         // 3: StaffEmployee
	(*SRecord)(nil),               // 4: SRecord
	(*SStatus)(nil),               // 5: SStatus
	(*StatusWithEmployee)(nil),    // 6: StatusWithEmployee
	(*GetStaffPropResp)(nil),      // 7: GetStaffPropResp
	(*StaffProp)(nil),             // 8: StaffProp
	(*GiveReq)(nil),               // 9: GiveReq
	(*GetEmployeeReq)(nil),        // 10: GetEmployeeReq
	(*GetRecordResp)(nil),         // 11: GetRecordResp
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_api_staff_proto_depIdxs = []int32{
	3,  // 0: GetResp.Staff:type_name -> StaffEmployee
	12, // 1: StaffEmployee.CreatedAt:type_name -> google.protobuf.Timestamp
	12, // 2: SRecord.CreatedAt:type_name -> google.protobuf.Timestamp
	3,  // 3: StatusWithEmployee.Employee:type_name -> StaffEmployee
	8,  // 4: GetStaffPropResp.Props:type_name -> StaffProp
	12, // 5: StaffProp.CreatedAt:type_name -> google.protobuf.Timestamp
	12, // 6: StaffProp.GivenAt:type_name -> google.protobuf.Timestamp
	3,  // 7: GetRecordResp.Emp:type_name -> StaffEmployee
	8,  // 8: GetRecordResp.Prop:type_name -> StaffProp
	12, // 9: GetRecordResp.Date:type_name -> google.protobuf.Timestamp
	3,  // 10: Staff.CreateEmployee:input_type -> StaffEmployee
	0,  // 11: Staff.GetStaff:input_type -> GetReq
	10, // 12: Staff.GetEmployee:input_type -> GetEmployeeReq
	4,  // 13: Staff.GetRecord:input_type -> SRecord
	0,  // 14: Staff.GetCount:input_type -> GetReq
	3,  // 15: Staff.GetStaffProp:input_type -> StaffEmployee
	9,  // 16: Staff.GiveToEmployee:input_type -> GiveReq
	9,  // 17: Staff.TakeFromEmployee:input_type -> GiveReq
	9,  // 18: Staff.IsWithEmployee:input_type -> GiveReq
	6,  // 19: Staff.CreateEmployee:output_type -> StatusWithEmployee
	1,  // 20: Staff.GetStaff:output_type -> GetResp
	3,  // 21: Staff.GetEmployee:output_type -> StaffEmployee
	11, // 22: Staff.GetRecord:output_type -> GetRecordResp
	2,  // 23: Staff.GetCount:output_type -> CountResp
	7,  // 24: Staff.GetStaffProp:output_type -> GetStaffPropResp
	5,  // 25: Staff.GiveToEmployee:output_type -> SStatus
	5,  // 26: Staff.TakeFromEmployee:output_type -> SStatus
	5,  // 27: Staff.IsWithEmployee:output_type -> SStatus
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_staff_proto_init() }
func file_api_staff_proto_init() {
	if File_api_staff_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_staff_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_staff_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_staff_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_staff_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaffEmployee); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_staff_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_staff_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_staff_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusWithEmployee); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_staff_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStaffPropResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_staff_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaffProp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_staff_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GiveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_staff_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEmployeeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_staff_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRecordResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_staff_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_staff_proto_goTypes,
		DependencyIndexes: file_api_staff_proto_depIdxs,
		MessageInfos:      file_api_staff_proto_msgTypes,
	}.Build()
	File_api_staff_proto = out.File
	file_api_staff_proto_rawDesc = nil
	file_api_staff_proto_goTypes = nil
	file_api_staff_proto_depIdxs = nil
}
